;==============================================================
; TILES FOR SPRITE 2 - (12 tiles total)
;==============================================================
; This data was generated by Beehive (see BigEvilCorporation's
; GitHub for source). BMP2TILE is another tool that can convert
; an image to this data format.
;
; Note that sprite tiles are layed out in COLUMN MAJOR, not
; row major like plane A/B cells.
;==============================================================

	dc.l	$00000000
	dc.l	$00000000
	dc.l	$00000000
	dc.l	$00000000
	dc.l	$00000000
	dc.l	$00000002
	dc.l	$00000002
	dc.l	$00000112

	dc.l	$00001222
	dc.l	$00012772
	dc.l	$00012772
	dc.l	$00012222
	dc.l	$00012222
	dc.l	$00012777
	dc.l	$00012777
	dc.l	$00012777

	dc.l	$00001222
	dc.l	$00001112
	dc.l	$00001112
	dc.l	$00000001
	dc.l	$00000000
	dc.l	$00000000
	dc.l	$00000000
	dc.l	$00000000

	dc.l	$00000000
	dc.l	$00000000
	dc.l	$00000000
	dc.l	$00000000
	dc.l	$02212222
	dc.l	$1227777A
	dc.l	$1227777A
	dc.l	$2777AAAA

	dc.l	$7777EEEA
	dc.l	$777EEEEE
	dc.l	$777EEEEE
	dc.l	$777EEEEE
	dc.l	$7777EEE7
	dc.l	$27777777
	dc.l	$27777777
	dc.l	$22222777

	dc.l	$22222222
	dc.l	$21111111
	dc.l	$21111111
	dc.l	$11114448
	dc.l	$00018EEE
	dc.l	$00048EEE
	dc.l	$00048EEE
	dc.l	$00004448

	dc.l	$00000000
	dc.l	$00000000
	dc.l	$00000000
	dc.l	$00000000
	dc.l	$22221220
	dc.l	$A7777221
	dc.l	$A7777221
	dc.l	$AAAA7772

	dc.l	$AAAEE777
	dc.l	$AAAEE777
	dc.l	$AAAEE777
	dc.l	$AAAA7777
	dc.l	$77777777
	dc.l	$7777777A
	dc.l	$7777777A
	dc.l	$7772222A

	dc.l	$22222222
	dc.l	$11111112
	dc.l	$11111112
	dc.l	$84441111
	dc.l	$88841000
	dc.l	$88844000
	dc.l	$88844000
	dc.l	$84440000

	dc.l	$00000000
	dc.l	$00000000
	dc.l	$00000000
	dc.l	$00000000
	dc.l	$00000000
	dc.l	$20000000
	dc.l	$20000000
	dc.l	$21100000

	dc.l	$22210000
	dc.l	$72221000
	dc.l	$72221000
	dc.l	$72221000
	dc.l	$72221000
	dc.l	$A2221000
	dc.l	$A2221000
	dc.l	$A2221000

	dc.l	$22210000
	dc.l	$21110000
	dc.l	$21110000
	dc.l	$10000000
	dc.l	$00000000
	dc.l	$00000000
	dc.l	$00000000
	dc.l	$00000000