;==============================================================
; TILES FOR SPRITE 1 - (4 tiles total)
;==============================================================
; This data was generated by Beehive (see BigEvilCorporation's
; GitHub for source). BMP2TILE is another tool that can convert
; an image to this data format.
;
; Note that sprite tiles are layed out in COLUMN MAJOR, not
; row major like plane A/B cells.
;==============================================================

	dc.l	$00000888
	dc.l	$00007788
	dc.l	$00077788
	dc.l	$07078888
	dc.l	$07768868
	dc.l	$87711111
	dc.l	$08762218
	dc.l	$88872228

	dc.l	$88876677
	dc.l	$00878877
	dc.l	$88888888
	dc.l	$08878888
	dc.l	$00887788
	dc.l	$00807788
	dc.l	$00088788
	dc.l	$00000808

	dc.l	$80800000
	dc.l	$77888000
	dc.l	$88880800
	dc.l	$88887880
	dc.l	$86886780
	dc.l	$11111888
	dc.l	$71226780
	dc.l	$82226800

	dc.l	$78668878
	dc.l	$88888888
	dc.l	$88888888
	dc.l	$88888080
	dc.l	$87888880
	dc.l	$88788800
	dc.l	$00887000
	dc.l	$80700000